# fly.toml app configuration file generated for 9c-market on 2025-03-12T22:14:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '9c-market'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
